Log emag errors; Stop product notify if different affiliate id;
vtex-apps/emag-integration pull request #5
Opened 2022-04-21 15:57 UTC by RaduGabor

2022-04-26 07:31 UTC, andreeacalinvtex requested changes
Remove console logs

2022-04-26 07:31 UTC, andreeacalinvtex commented on node/routes/productNotify.ts
> +    console.log(`Product ${body.ProductId} and SKU ${body.IdSku} has another affiliateId: ${body.IdAffiliate}. Required affiliateId: ${appSettings.affiliateId}`)
Do we need this console.log here? I think we can use instead the VTEX logger option

2022-04-26 07:31 UTC, andreeacalinvtex commented on node/routes/productNotify.ts
> +  console.log("PRODUCT NOTIFY", body, vtex);
and here?

2022-04-26 08:31 UTC, andreeacalinvtex commented on node/routes/productNotify.ts
> +    console.log(`Product ${body.ProductId} and SKU ${body.IdSku} has another affiliateId: ${body.IdAffiliate}. Required affiliateId: ${appSettings.affiliateId}`)
Do we need this console.log here? I think we can use instead the VTEX logger option

2022-04-27 12:32 UTC, RaduGabor commented
Done, added Vtex Logger

2022-04-28 07:15 UTC, andreeacalinvtex approved these changes

2022-05-02 10:51 UTC, merged